server:
  port: 8080

spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:mysql://localhost:3306/identysafe_db}
    username: ${SPRING_DATASOURCE_USERNAME:root}
    password: ${SPRING_DATASOURCE_PASSWORD:Sachintha@2003}
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
    show-sql: true
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://api.asgardeo.io/t/sporg/oauth2/token
          jwk-set-uri: https://api.asgardeo.io/t/sporg/oauth2/jwks

cloudinary:
  cloud-name: dcblrfg9m
  api-key: 871257782914546
  api-secret: aqx4DqGBtWbXY2YUdilmTrvCP6s
